### ISSUE TITLE
Ошибка NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by kurlo** [burbilog/scrapbook2zotero#1]
При запуске выдавало ошибку 
Traceback (most recent call last):
  File "./scrapbook2zotero.py", line 524, in <module>
    main(sys.argv[1:])
  File "./scrapbook2zotero.py", line 496, in main
    root, items = open_scrapbook_rdf(Args.scrapbookdir)
  File "./scrapbook2zotero.py", line 237, in open_scrapbook_rdf
    root = load_node('', items['urn:scrapbook:root'], items)
  File "./scrapbook2zotero.py", line 143, in load_node
    node = Node(nodeid, item)
  File "./scrapbook2zotero.py", line 117, in __init__
    self.type = unicode(item['NS1:type']) if item is not None else ''
NameError: name 'unicode' is not defined

Поменял везде unicode на str. Вроде заработало

**Comment by burbilog** [comment]
Потому что вы запускаете скрипт под третьтим питоном, а он написан для второго (а для второго. чтобы виндовые бинарники было проще собирать под wine). Так что это не совсем баг, а типичное расхождение версий.

Прикрутить проверку версии питона что-ли...

**Comment by kurlo** [comment]
Да я так и понял, что это связано с версией. У меня установлен и второй питон, видимо для совместимости, но он видимо не увидел rdflib, который я установил и не захотел запускать скрипт

**Comment by burbilog** [comment]
Добавил жесткую проверку на версию питона, чтобы сразу показывало в чем дело.
