### ISSUE TITLE
Import only imports website names but not html or pdf files

### ISSUE THREAD

**Issue by manuelkleiner** [burbilog/scrapbook2zotero#2]
Thanks for creating this tool. I have successfully generated the .RDF files with it for my scrapbook and I am able to import them into zotero. The issue is that the import to Zotero only adds the list of websites to Zotero, but not the html and PDF files that I had associated with the websites in scrapbook. How can I ensure that the actual website snapshots and pdf files from scrapbook are imported as well. Clearly these files cannot be embedded in the RDF file itself, so I somehow must link the scrapbook datafolder. 
Any hints on how to solve this would be greatly appreciated.

**Comment by manuelkleiner** [comment]
Ok I found the problem. The line that contains the location information for scrapbook data for some reason as both the '\' and the '/' character in the file path e.g.
 <rdf:resource rdf:resource="c:\Arbeit\ScrapBook\GeneralInterestScience/data/20190306102553/index.html"/>

So if you use the tool of your choice e.g. sed in linux you can make sure all '/' are turned into '\'. Then the import works without problems. You just have to make sure to only change this in the rdf:resource field though and not in other field e.g. with the URL.

**Comment by burbilog** [comment]
Yes, this looks like a bug. I have limited experience with Windows, I tested scrapbook2zotero in Win10 and worked okay, including file import, so I thought that windows can handle both slashes and backslashes at once.

**Comment by burbilog** [comment]
I think I fixed this problem. Please, try new version https://github.com/burbilog/scrapbook2zotero/releases/download/v1.0.3/scrapbook2zotero-v1.0.3.zip and if everything is ok, i'll close the issue.

**Comment by manuelkleiner** [comment]
Yes that fixed it. Thank you!
